package sqlite;
// Generated 17-ene-2020 14:20:42 by Hibernate Tools 4.3.1



/**
 * Ciudad generated by hbm2java
 */
public class Ciudad  implements java.io.Serializable {


     private int id;
     private Lugar lugar;
     private String nombre;
     private String pais;
     private String provincia;
     private String edificioEmblematico;

    public Ciudad() {
    }

	
    public Ciudad(int id) {
        this.id = id;
    }
    public Ciudad(int id, Lugar lugar, String nombre, String pais, String provincia, String edificioEmblematico) {
       this.id = id;
       this.lugar = lugar;
       this.nombre = nombre;
       this.pais = pais;
       this.provincia = provincia;
       this.edificioEmblematico = edificioEmblematico;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Lugar getLugar() {
        return this.lugar;
    }
    
    public void setLugar(Lugar lugar) {
        this.lugar = lugar;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getEdificioEmblematico() {
        return this.edificioEmblematico;
    }
    
    public void setEdificioEmblematico(String edificioEmblematico) {
        this.edificioEmblematico = edificioEmblematico;
    }




}


