package sqlite;
// Generated 13-ene-2020 14:19:35 by Hibernate Tools 4.3.1



/**
 * Ciudades generated by hbm2java
 */
public class Ciudades  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String pais;
     private String provincia;
     private String edificioEmblematico;
     private String lugar;

    public Ciudades() {
    }

	
    public Ciudades(int id) {
        this.id = id;
    }
    public Ciudades(int id, String nombre, String pais, String provincia, String edificioEmblematico, String lugar) {
       this.id = id;
       this.nombre = nombre;
       this.pais = pais;
       this.provincia = provincia;
       this.edificioEmblematico = edificioEmblematico;
       this.lugar = lugar;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getEdificioEmblematico() {
        return this.edificioEmblematico;
    }
    
    public void setEdificioEmblematico(String edificioEmblematico) {
        this.edificioEmblematico = edificioEmblematico;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }




}


