package sqlite;
// Generated 13-ene-2020 14:19:35 by Hibernate Tools 4.3.1



/**
 * Grupos generated by hbm2java
 */
public class Grupos  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String nombreDirector;
     private Integer edadMinima;
     private String horario;
     private String nombrePersona;

    public Grupos() {
    }

	
    public Grupos(int id) {
        this.id = id;
    }
    public Grupos(int id, String nombre, String nombreDirector, Integer edadMinima, String horario, String nombrePersona) {
       this.id = id;
       this.nombre = nombre;
       this.nombreDirector = nombreDirector;
       this.edadMinima = edadMinima;
       this.horario = horario;
       this.nombrePersona = nombrePersona;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getNombreDirector() {
        return this.nombreDirector;
    }
    
    public void setNombreDirector(String nombreDirector) {
        this.nombreDirector = nombreDirector;
    }
    public Integer getEdadMinima() {
        return this.edadMinima;
    }
    
    public void setEdadMinima(Integer edadMinima) {
        this.edadMinima = edadMinima;
    }
    public String getHorario() {
        return this.horario;
    }
    
    public void setHorario(String horario) {
        this.horario = horario;
    }
    public String getNombrePersona() {
        return this.nombrePersona;
    }
    
    public void setNombrePersona(String nombrePersona) {
        this.nombrePersona = nombrePersona;
    }




}


