package sqlite;
// Generated 13-ene-2020 14:19:35 by Hibernate Tools 4.3.1



/**
 * Lugares generated by hbm2java
 */
public class Lugares  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String direccion;
     private Integer numeroEdif;
     private String horario;
     private String grupo;

    public Lugares() {
    }

	
    public Lugares(int id) {
        this.id = id;
    }
    public Lugares(int id, String nombre, String direccion, Integer numeroEdif, String horario, String grupo) {
       this.id = id;
       this.nombre = nombre;
       this.direccion = direccion;
       this.numeroEdif = numeroEdif;
       this.horario = horario;
       this.grupo = grupo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getNumeroEdif() {
        return this.numeroEdif;
    }
    
    public void setNumeroEdif(Integer numeroEdif) {
        this.numeroEdif = numeroEdif;
    }
    public String getHorario() {
        return this.horario;
    }
    
    public void setHorario(String horario) {
        this.horario = horario;
    }
    public String getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(String grupo) {
        this.grupo = grupo;
    }




}


