package sqlite;
// Generated 13-ene-2020 14:19:35 by Hibernate Tools 4.3.1



/**
 * Personas generated by hbm2java
 */
public class Personas  implements java.io.Serializable {


     private int id;
     private String nombre;
     private Double altura;
     private Double peso;
     private Integer edad;

    public Personas() {
    }

	
    public Personas(int id) {
        this.id = id;
    }
    public Personas(int id, String nombre, Double altura, Double peso, Integer edad) {
       this.id = id;
       this.nombre = nombre;
       this.altura = altura;
       this.peso = peso;
       this.edad = edad;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Double getAltura() {
        return this.altura;
    }
    
    public void setAltura(Double altura) {
        this.altura = altura;
    }
    public Double getPeso() {
        return this.peso;
    }
    
    public void setPeso(Double peso) {
        this.peso = peso;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }




}


