package sqlite;
// Generated 17-ene-2020 14:20:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by hbm2java
 */
public class Grupo  implements java.io.Serializable {


     private int id;
     private Persona persona;
     private String nombre;
     private String nombreDirector;
     private Integer edadMinima;
     private String horario;
     private Set lugars = new HashSet(0);

    public Grupo() {
    }

	
    public Grupo(int id) {
        this.id = id;
    }
    public Grupo(int id, Persona persona, String nombre, String nombreDirector, Integer edadMinima, String horario, Set lugars) {
       this.id = id;
       this.persona = persona;
       this.nombre = nombre;
       this.nombreDirector = nombreDirector;
       this.edadMinima = edadMinima;
       this.horario = horario;
       this.lugars = lugars;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getNombreDirector() {
        return this.nombreDirector;
    }
    
    public void setNombreDirector(String nombreDirector) {
        this.nombreDirector = nombreDirector;
    }
    public Integer getEdadMinima() {
        return this.edadMinima;
    }
    
    public void setEdadMinima(Integer edadMinima) {
        this.edadMinima = edadMinima;
    }
    public String getHorario() {
        return this.horario;
    }
    
    public void setHorario(String horario) {
        this.horario = horario;
    }
    public Set getLugars() {
        return this.lugars;
    }
    
    public void setLugars(Set lugars) {
        this.lugars = lugars;
    }
    
    
 



}


