/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cristofinity;

import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author aleja
 */
public class MostrarCatalogo extends javax.swing.JFrame{

    /**
     * Creates new form MostrarCatalogo
     */
      
    String endl = System.getProperty("line.separator");

    public static ArrayList<Multimedia> lista = new ArrayList();
    
    public MostrarCatalogo() {
        

        initComponents();
        this.setTitle("Catalogo");
        this.setLocationRelativeTo(this);
        this.setResizable(false);
        
       
        
        int tamaño = MostrarCatalogo.lista.size();
        final String[] vector = new String[tamaño];
        for(int a = 0; a < tamaño; a++){
            vector[a] = ( "Titulo: " + MostrarCatalogo.lista.get(a).getTitulo());
        }
        
        this.jList1.setModel(new javax.swing.AbstractListModel(){
            String[] vect = vector;
            
            @Override
            public int getSize() {
                return vect.length;
            }

            @Override
            public Object getElementAt(int i) {
                return vect[i];
            }
        
        });
        
        
        jTextField1.setText(String.valueOf(lista.size()));
        jList1.setCellRenderer(new CristoFinity());
    }
    
    public String atributosMultimedia(Multimedia p){
   
        String media = "Titulo: " + p.getTitulo() + endl + "Genero: " + p.getGenero() + endl + "Fecha de publicacion: " +  p.getFechaPublicacion() + endl+ "Duracion en seg: " + p.getDuracionEnSegundos() + endl + "Pegi: " + p.getPegi() + endl;

        return media;
     
    }
    
    public String atributosSerie(Serie p){
        
        String atributos = atributosPelicula(p);
        
        atributos += "Temporadas: " + p.getTemporadas() + endl + "Capitulos: " + p.getCapitulos() + endl;
        return atributos;
    }
    
    public String atributosPelicula(Pelicula p){
       
        String atributos = atributosMultimedia(p);
        
        atributos += "Productor: " + p.getProductor() + endl + "Direccion: " + p.getDireccion() + endl + "Guion: " + p.getGuion() + endl + "Reparto:" + p.getReparto() + endl;
        
        return atributos;
    }
    
    public String atributosCancion(Cancion p){
        String atributos = atributosMultimedia(p);
        
        atributos += "Album: " + p.getAlbum() + endl + "Artista: " + p.getArtista() + endl;
        
        return atributos;
    }
    
    public String atributosVideojuego(Videojuego p){
        
        String atributos = atributosMultimedia(p);
        
        atributos += "Editor: " + p.getEditor() + endl + "Desarrollador: " + p.getDesarrollador() + endl + "Plataforma: " + p.getPlataforma() + endl + "Jugadores:" + p.getJugadores() + endl;
        
        return atributos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("LISTA DE MULTIMEDIAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 173, 32));

        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 56, 494, 347));

        jButton1.setText("VER INFORMACION");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 77, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Total Multimedias");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        jButton2.setText("Atras");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 431, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\aleja\\Documents\\NetBeansProjects\\CristoFinity\\mostrarCatakigi.jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ImageIcon pelicula = new ImageIcon("platanos.PNG");
    ImageIcon serie = new ImageIcon("serieCartel.jpg");
    ImageIcon cancion = new ImageIcon("fotoCancion.png");
    ImageIcon videojuego = new ImageIcon("bo4.jpg");
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        this.setVisible(false);
             
        Informacion ventanaInfo = new Informacion();
       
      
       ventanaInfo.setResumenToLabel(MostrarCatalogo.lista.get(this.jList1.getSelectedIndex()).getResumen());
       
       if(MostrarCatalogo.lista.get(this.jList1.getSelectedIndex()) instanceof Serie){
            ventanaInfo.setTextMedia(atributosSerie((Serie) MostrarCatalogo.lista.get(this.jList1.getSelectedIndex())));
            ventanaInfo.setImageToJLabel(serie);

       } else if (MostrarCatalogo.lista.get(this.jList1.getSelectedIndex()) instanceof Pelicula){
            ventanaInfo.setTextMedia(atributosPelicula((Pelicula) MostrarCatalogo.lista.get(this.jList1.getSelectedIndex())));
            ventanaInfo.setImageToJLabel(pelicula);

       }else if (MostrarCatalogo.lista.get(this.jList1.getSelectedIndex()) instanceof Cancion){
            ventanaInfo.setTextMedia(atributosCancion((Cancion) MostrarCatalogo.lista.get(this.jList1.getSelectedIndex())));
            ventanaInfo.setImageToJLabel(cancion);

       }else if (MostrarCatalogo.lista.get(this.jList1.getSelectedIndex()) instanceof Videojuego){
            ventanaInfo.setTextMedia(atributosVideojuego((Videojuego) MostrarCatalogo.lista.get(this.jList1.getSelectedIndex())));
            ventanaInfo.setImageToJLabel(videojuego);
       }
       
       ventanaInfo.setVisible(true);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
